language: "node_js"

os:
  - "linux"
  - "osx"

node_js:
  - "node"
  - "7"
  - "6"
  - "5"
  - "4"

sudo: "required"
dist: "xenial"

install:
  - "npm install --ignore-scripts"
  - "npm run build"

before_install:
  - "if [ $TRAVIS_OS_NAME == 'linux' ]; then sudo add-apt-repository --yes ppa:stebbins/handbrake-releases; fi"
  - "if [ $TRAVIS_OS_NAME == 'linux' ]; then sudo apt-get update -qq; fi"
  - "if [ $TRAVIS_OS_NAME == 'linux' ]; then sudo apt-get install -qq handbrake-cli; fi"
  - "if [ $TRAVIS_OS_NAME == 'linux' ]; then sudo chmod 777 /usr/bin/HandBrakeCLI; fi"
