language: node_js
os:
  - "linux"
  - "osx"
node_js:
  - "node"
  - "7"
  - "6"
  - "5"
  - "4"

before_install:
  - sudo add-apt-repository --yes ppa:stebbins/handbrake-releases
  - sudo apt-get update -qq
  - sudo apt-get install -qq handbrake-cli
